-- liquibase formatted sql

-- changeset oalekseenko:1
create table if not exists users (
    id bigint generated by default as identity primary key,
    first_name varchar(255),
    last_name  varchar(255),
    username   varchar(255) unique not null,
    city       varchar(255),
    enabled    boolean not null,
    password   varchar(255),
    phone      varchar(255),
    reg_date   timestamp
);

create table if not exists authorities (
    username  varchar(255) not null primary key,
    authority varchar(32)
);

create table if not exists ads (
    id          bigint generated by default as identity primary key,
    description varchar(255),
    price       numeric(19, 2),
    title       varchar(255),
    user_id     bigint references users(id) on delete cascade
);

create table if not exists avatars (
    id      bigint generated by default as identity primary key,
    image   bytea,
    user_id bigint unique references users (id) on delete cascade
);

create table if not exists comments (
    id         bigint generated by default as identity primary key,
    created_at timestamp,
    text       varchar(255),
    ads_id     bigint references ads (id) on delete cascade,
    user_id    bigint references users (id) on delete cascade
);

create table if not exists images (
    id         bigint generated by default as identity primary key,
    data       bytea,
    file_size  bigint,
    media_type varchar(255),
    ads_id     bigint references ads (id) on delete cascade
);

